
services:
  dev-db:
    image: postgres:16.1-alpine3.19
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - dev-db-data:/var/lib/posgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
     - POSTGRES_USER
     - POSTGRES_PASSWORD
     - POSTGRES_DB
volumes:
  dev-db-data: